module.exports = {
    printWidth: 160,
    tabWidth: 4,
    useTabs: false,
    semi: true,
    singleQuote: true,
    quoteProps: 'as-needed',
    jsxSingleQuote: false,
    trailingComma: 'all', //"es5",
    bracketSpacing: true,
    jsxBracketSameLine: true,
    arrowParens: 'always',
    rangeStart: 0,
    rangeEnd: Infinity,
    requirePragma: false,
    insertPragma: false,
    proseWrap: 'always',
    htmlWhitespaceSensitivity: 'css',
    endOfLine: 'auto',
};
